# Generated by Django 4.1.1 on 2022-09-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
