# Generated by Django 4.1.1 on 2022-09-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoApp', '0003_customer_groups_customer_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
